all: button

PROJECTDIRS += ..
APPS = serial-shell
PROJECT_SOURCEFILES += dag_node.c int-flash-common.c ota-main.c ota-common.c crypto-common.c system-common.c rtc-common.c
DEFINES+=PROJECT_CONF_H=\"project-conf-class-c.h\"
DEFINES+=UMDK_4BTN=1
DEFINES+=CLASS=0x0C
DEFINES+=UNWDS_MODULE_ID=2
CONTIKI = ../..
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
include $(CONTIKI)/Makefile_git_version.include
