### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

include $(PLATFORM_ROOT_DIR)/softel_lighting_board/Makefile.softel_lighting_board

CONTIKI_TARGET_DIRS += softel_lighting_board/cc13xx
